### PR TITLE
Deserialisation exceptions message

### PR DESCRIPTION
**Pull request by StefanoChiodino**
Helps with #204.

Results in:

image

I wasn't sure about what type of exception, so I'm following https://stackoverflow.com/questions/12824222/what-kind-of-exception-should-i-use-for-no-record-found-c but could easilly be just of `Exception` type.

Cheers.

### CODE REVIEW

**Comment by KevinJump** [comment]
thanks, I actually think it shouldn't throw, if the master can't be found by key, then it should check! (which is  was an issue there 😄 ) - but carry on. 

in the next bit of the file if the masterId is still 0 it does an 'old school' lookup, which is it does it by alias - ideally it should be falling through to that.

**Comment by StefanoChiodino** [comment]
How can it search more for it? We only have the guid at that point!

**Comment by KevinJump** [comment]
We also have the alias, 

so the Master node is in the form ```<Master Key="{guid}">data</Master>``` where the value is the alias.

in the code just below the fix we use the node value to do a lookup by alias. 

```
If (masterId == 0)
{
  // old school alias lookup
  var master = default(IContentTypeBase);

  LogHelper.Debug<Events>("Looking up Content Master by Alias");
  var masterAlias = masterNode.Value;
  master = LookupByAlias(masterAlias);
  if (master != null)
       masterId = master.Id;
}
```
So where we currently throw an exception when it's null, all we need to do is let the code fall through to this and it will do an Alias lookup instead.

**Comment by StefanoChiodino** [comment]
Ah, what a fool, of course we do, is right there!

Ok then, so inside the if, search by alias, if not found then throw?

**Comment by KevinJump** [comment]
Don't think we need to throw at all - just check for the null in the key lookup, and let if fall through the alias and subsequently to the code below. 

if at the end of the lookup the MasterId is still 0 (which it would be if it wasn't found) then we just don't set the master of the doctype. this isn't always a disaster, the rest of the doctype can still be created. and if at a later date the master is actually created a subsequent run through would set it and everything would be fine

**Comment by StefanoChiodino** [comment]
The reason for throwing is so that we can control what gets into the log. Which was the point to begin with: if something goes wrong with the files we know how to fix it. Guess we could just log instead, then let it fail?

**Comment by StefanoChiodino** [comment]
I guess it boils down to fail hard or not. To me, failing to get the master by both id and alias means we shouldn't proceed, and as long as the message it clear it would be best to fix this (e.g. add a doctype with that alias). While doing this after through the UI is not easy.

**Comment by KevinJump** [comment]
yeah, i have always taken the view, try and get as close as possible - there are so many random things people do that can nearly break stuff! 

having said that a missing master doctype is quite a fail, the structure of the uSync folders means it really should exist in the folder above and be processed first, so it missing means something has happened (probably why this issue hasn't come up before)

**Comment by StefanoChiodino** [comment]
In my case I moved (e.g. deleted and recreated) the master somewhere else, that's why the ID was different, so as it stand this will still fix my problem, and give a much better error, while still failing hard.

**Comment by KevinJump** [comment]
Hi, sorry can you confirm what version you were seeing this on? 

just realised the PR is to dev7_7 branch which isn't the master branch (v4_master is) and in that branch, the null checking is there.  

(https://github.com/KevinJump/uSync/pull/228) 
has been since 4.0.12 

its also changed in v-latest release because of entity service issues in 7.15.0 (see it now https://github.com/KevinJump/uSync/blob/v4_master/Jumoo.uSync.Core/Serializers/ContentTypeBaseSerializer.cs#L87)

so in theory v4.0.12+ should never get this error :(

**Comment by StefanoChiodino** [comment]
Sorry for the delay.

Ah, I was using 4.0.8 so that makes sense. Also wasn't sure about the branch names so I just went with the most obvious branch name I could find!

The code you linked seems to be lacking logging and throwing. At the end of the whole master block should it not throw if it wasn't found at all?

**Pull request merged**
