### PR TITLE
Missing handlers serializers

### PR DESCRIPTION
**Pull request by takinosaji**

### CODE REVIEW

**Comment by takinosaji** [comment]
@KevinJump Missing files are here

**Comment by takinosaji** [comment]
@KevinJump 

There are situations when we need execute custom logic before user serialized for instance - wiping of permissions. 
Problem here that we have to ensure sequential order of invocation of umbraco event handlers which might be tricky. So when we are using usync let us have a place where execute our custom logic upon saving of user and ensure that all is done inside one handler.

That's why we propose such changes to user handler. Thanks!

**Comment by takinosaji** [comment]
@KevinJump  Hi Kevin. Can we expect our changes become a part of usync soon?)

**Comment by takinosaji** [comment]
@KevinJump ping)

**Comment by KevinJump** [comment]
Sorry, properly busy - I have half done it - but i wanted to test as it quite a lot to add. 

I was wondering about splitting most of it into a seperate package (maybe uSync.peopleEdition) - so that there is less of an inter-dependency, and then in theory updates can happen quicker - but in reality i just haven't had the time to look at it in the last month .

next week looks good though 😄

**Pull request closed without merging**
