### PR TITLE
4 new handlers with serializers and all required stuff were added: Us…

### PR DESCRIPTION
**Pull request by takinosaji**
Hi-ho. 
For our purposes we have been requiring some functionality which uSync still misses and implemented it on our own and want to share it with hope that it will help other teams and projects as uSync helped us.

4 new handlers with serializers and all required stuff were added: UserHandler, UserTypeHandler, MemberGroupHandler, MemberHandler. New handlers include some improvements like ensuring that old serialized folder will be removed if entity has been renamed and etc, and xml validation logic added.

### CODE REVIEW

**Comment by KevinJump** [comment]
thanks - this has been merged into the uSync_3.4 branch - https://github.com/KevinJump/uSync/tree/uSync_3.4 and will form part of the next version bump release.

**Comment by KevinJump** [comment]
Hi, 

actually getting to look at these now, the PR is missing files :( 

in usync core /extensions/umbraco, 

I am guessing its excluded because the .gitignore excludes the umbraco folder.

**Comment by takinosaji** [comment]
@KevinJump Hi. I have added files and pushed it to repository and created pull request.
https://github.com/KevinJump/uSync/pull/133

Thanks!

**Comment by takinosaji** [comment]
@KevinJump have i committed changes correct? Do i need to change anything?

**Comment by KevinJump** [comment]
HI, its next on my list :) just had to push some minor picker things out, and didn't want to get them all mixed up with bigger changes, so I moved things around in the intended releases. 

The next release will be 3.4 which should have this in.

**Pull request closed without merging**
